{% set version = "0.7.1" %}

package:
  name: py2cytoscape
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/py2cytoscape/py2cytoscape-{{ version }}.tar.gz
  sha256: 473a4c7aab2ca0b406c4052560c3bf149c625c20d6528ff4a56e923939fd5430

build:
  number: 3
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - networkx
    - pandas
    - pydot
    - pydotplus
    - pyparsing
    - python >={{ python_min }}
    - python-igraph
    - requests

test:
  requires:
    - ipython
    - jinja2
    - scipy
    - pip
    - python {{ python_min }}
    # upstream changed PyPI/module name: https://github.com/conda-forge/python-igraph-feedstock/pull/50
    - python-igraph <0.9.8
  imports:
    - py2cytoscape
    - py2cytoscape.cyrest
    - py2cytoscape.data.network_client
    - py2cytoscape.data.table
    - py2cytoscape.util
    - py2cytoscape.util.cytoscapejs
    - py2cytoscape.util.util_dataframe
    - py2cytoscape.util.util_graphlab
    - py2cytoscape.util.util_igraph
    - py2cytoscape.util.util_networkx
    - py2cytoscape.util.util_numpy
  commands:
    - pip check

about:
  home: https://github.com/cytoscape/py2cytoscape
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python utilities for Cytoscape and Cytoscape.js
  doc_url: https://py2cytoscape.readthedocs.io
  dev_url: https://github.com/cytoscape/py2cytoscape

extra:
  recipe-maintainers:
    - bollwyvl
