{% set name = "py2cytoscape" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 473a4c7aab2ca0b406c4052560c3bf149c625c20d6528ff4a56e923939fd5430

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py2k or win]

requirements:
  build:
    - python
    - pip
  run:
    - networkx
    - pandas
    - pydot
    - pydotplus
    - pyparsing
    - python
    - python-igraph
    - requests

test:
  requires:
    - ipython
    - jinja2
    - scipy
  imports:
    - py2cytoscape
    - py2cytoscape.cyrest
    - py2cytoscape.data.network_client
    - py2cytoscape.data.table
    - py2cytoscape.util
    - py2cytoscape.util.cytoscapejs
    - py2cytoscape.util.util_dataframe
    - py2cytoscape.util.util_graphlab
    - py2cytoscape.util.util_igraph
    - py2cytoscape.util.util_networkx
    - py2cytoscape.util.util_numpy

about:
  home: https://github.com/cytoscape/py2cytoscape
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python utilities for Cytoscape and Cytoscape.js
  doc_url: https://py2cytoscape.readthedocs.io
  dev_url: https://github.com/cytoscape/py2cytoscape

extra:
  recipe-maintainers:
    - bollwyvl
