# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yWyMRp1mgElhgZuXxBrkcqxMZ25yzYIkk4/MwCPeFPxla8/gSocZxHXuU83fYkysJe3gxI9izrllbOFoHe6mHQf3IPQmTmlHxD9HJS5iRvJhBO75X94Ld4NOnhrxEw8crPNrDVQec3kCb/2PsKRihiWiugUj+v6roVgJzV4f1PwxQAYwip92MfdGIIABjYZYvG4PYog588Y68VOHVJQi+PWzpOVoE50uMwiPFW80zfBQZWt9d+hqXJyBo29uZ400q9ZyAsjk4bg0hgrw4wZ/l0nvDfviLkLMMdOVe5uUVaGBpGM96F6wKkqI1XWVuxwhgv96PWudmk3rl17LaxdovHNaebts/jxj+SLl8idI2wh8ltWrpyFOeZ0TH/dJEaa6tdm9OvUg+Nfzp3Klv0YXQXjRF0HSZrp1QnRkzFARv1jUZliJb0lsacqlsqx2c1F01/lZIdVyxPmnlQKU7hL4kuuODiCeaSTtoPUVTBBOgYltnAfLa+6agz3w3PWW57DaY+L+snoSypGYTJ2k+PCY2FCoBaHT/2uiS9BiszN8qqaogYfEyC4efc5qPRTCqfYqMep5iE+e0jypQe8n/wKu2XJJVCRx1E15ATmqfcE3aOgtJPg43HWppwGcU7w1hoFI/5Gfp9P8iguV0AWtEohQufrLrLZOtYbBnjmL/8433m4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
