travis:
  secure:
    BINSTAR_TOKEN: HMwhn3bKUPHzugDaK+hKGFO9Ev7flouIQWDiKB+wvsM/Rjzxq3cfKIoCNJ7BZ5+xKTqGF2ms4MOrTJAfsXOWrTZ4FYcLPr0yNVNdq4x50TRouE5+oLpED8d3EvVTnKOzGrdbZVIizQK9M3BZfffNIM4uOBACayueUWM+CuD5behD/30oSek4AW2DvGBZ5YiumZJqmUDHXl0x4wMROQT4z3VoxT/aYFNGMqEFQZWI7jNKhGMJzP/BYKLXhO7lhN2QF/3zWGVemOmBtqnuOu4wyIVcdrOA0C+C8Xpr81M1h2Ps4BF9PHU4CH/979Ip2mQAZAJeSG8e7Qkt/ukgSpolzeZrsgcFv+nuvXNcg1KFrOKTU3vevPFThDFG1L/LWF6wMPwqgBWLtape1jllE0LfPOvcEVEp+xnMkQu1jjcoPmeP3kP02Mj+eMzVZeods19qr3EKwe9dJn+93inotmvP7s64+JbEMNOGYbqiZGQolyQYqmo2YqywEaciitWoWEiI/EjRi2SWiX8Dp7Uq47TYQTdu+xe1To44zGKoZly36LAAn6WpFnDiTID7/PegGcj5MgSOmTMcuD1Z3SmCMyMlMEYJcz6g7X4ImoSGXxL7Em1uSa7vXdBNXmKB1jr6emFCyiqcIPzmI2AX55SoSGmWx7PsreYTPeNof2YqdpYo010=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
