travis:
  secure:
    BINSTAR_TOKEN: yWyMRp1mgElhgZuXxBrkcqxMZ25yzYIkk4/MwCPeFPxla8/gSocZxHXuU83fYkysJe3gxI9izrllbOFoHe6mHQf3IPQmTmlHxD9HJS5iRvJhBO75X94Ld4NOnhrxEw8crPNrDVQec3kCb/2PsKRihiWiugUj+v6roVgJzV4f1PwxQAYwip92MfdGIIABjYZYvG4PYog588Y68VOHVJQi+PWzpOVoE50uMwiPFW80zfBQZWt9d+hqXJyBo29uZ400q9ZyAsjk4bg0hgrw4wZ/l0nvDfviLkLMMdOVe5uUVaGBpGM96F6wKkqI1XWVuxwhgv96PWudmk3rl17LaxdovHNaebts/jxj+SLl8idI2wh8ltWrpyFOeZ0TH/dJEaa6tdm9OvUg+Nfzp3Klv0YXQXjRF0HSZrp1QnRkzFARv1jUZliJb0lsacqlsqx2c1F01/lZIdVyxPmnlQKU7hL4kuuODiCeaSTtoPUVTBBOgYltnAfLa+6agz3w3PWW57DaY+L+snoSypGYTJ2k+PCY2FCoBaHT/2uiS9BiszN8qqaogYfEyC4efc5qPRTCqfYqMep5iE+e0jypQe8n/wKu2XJJVCRx1E15ATmqfcE3aOgtJPg43HWppwGcU7w1hoFI/5Gfp9P8iguV0AWtEohQufrLrLZOtYbBnjmL/8433m4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
